<div id="descricao_produto">
	<div id="achocolatado">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/achocolatado_sache.png" alt="Achocolatado Sache" />
			<a href="<?php echo $this->basepath("tabloides/sache_achocolatado_instantaneo_flat.zip"); ?>" class="dow_mv" target="_blank">baixar a imagem da embalagem</a>	
            <a href="<?php echo $this->url('home'); ?>" class="choc" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>