<div id="descricao_produto">
	<div id="box_produto_gourmet">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/gourmet.png" alt="Seleto Gourmet" />
			<a href="<?php echo $this->basepath("tabloides/Pack-Goumet.zip"); ?>" class="dow_mr" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="mr" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>