<div id="descricao_produto">
	<div id="dom_levissimo">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/dom_levissimo.png" alt="Seleto Dom Levissimo" />
			<a href="<?php echo $this->basepath("tabloides/dom_levissimo.zip"); ?>" class="dow_le" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="lev" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>