<div id="descricao_produto">
	<div id="box_produto_forte">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/almofada_forte.png" alt="Seleto Forte" />
			<a href="<?php echo $this->basepath("tabloides/Seleto-Almofada-250-500-forte.zip"); ?>" class="dow_vm" target="_blank">baixar a imagem da embalagem</a>	
            <a href="<?php echo $this->url('home'); ?>" class="vm" title="VOLTAR PARA HOME">Fechar</a>				
		</div>
	</div>
</div>