<div id="descricao_produto">
	<div id="dom_intenso">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/dom_intenso.png" alt="Seleto Dom Intenso" />
			<a href="<?php echo $this->basepath("tabloides/dom_intenso.zip"); ?>" class="dow_in" target="_blank">baixar a imagem da embalagem</a>
			<a href="<?php echo $this->url('home'); ?>" class="int" title="VOLTAR PARA HOME">Fechar</a>
			
		</div>
	</div>
</div>