<div id="descricao_produto">
	<div id="box_produto_tradicional">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/pack-vacuo-500-tradicional.png" alt="Seleto Tradicional" />
			<a href="<?php echo $this->basepath("tabloides/Pack-Vacuo-250-500-Tradicional.zip"); ?>" class="dow_am" target="_blank">baixar a imagem da embalagem</a>
			<a href="<?php echo $this->url('home'); ?>" class="am" title="VOLTAR PARA HOME">Fechar</a>						
		</div>
	</div>
</div>