<div id="descricao_produto">
	<div id="box_produto_forte">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/stand_up.png" alt="Seleto Forte" />
			<a href="<?php echo $this->basepath("tabloides/Seleto-embalage-Stand-Up.zip"); ?>" class="dow_vm" target="_blank">baixar a imagem da embalagem</a>	
            <a href="<?php echo $this->url('home'); ?>" class="vm" title="VOLTAR PARA HOME">Fechar</a>				
		</div>
	</div>
</div>