<div id="descricao_produto">
	<div id="mistura_bolo_choc">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/misturaBolo_chocolate.png" alt="Mistura de Bolo" />
			<a href="<?php echo $this->basepath("tabloides/mistura_bolo_chocolate.zip"); ?>" class="dow_mr" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="bg" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>