<div id="descricao_produto">
	<div id="mistura_bolo_laranja">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/misturaBolo_laranja.png" alt="Mistura de Bolo" />
			<a href="<?php echo $this->basepath("tabloides/mistura_bolo_laranja.zip"); ?>" class="dow_la" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="lr" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>