<div id="descricao_produto">
	<div id="mistura_bolo_milho">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/misturaBolo_milho.png" alt="Mistura de Bolo" />
			<a href="<?php echo $this->basepath("tabloides/mistura_bolo_milho.zip"); ?>" class="dow_vd" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="vd" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>