<div id="descricao_produto">
	<div id="mistura_bolo_coco">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/misturaBolo_coco.png" alt="Mistura de Bolo" />
			<a href="<?php echo $this->basepath("tabloides/mistura_bolo_coco.zip"); ?>" class="dow_cz" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="br" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>