<div id="descricao_produto">
	<div id="preparo_morango">
		<div class="produto">	
			<img src="<?php echo $this->basepath(); ?>/img/produtos/sache_morango.png" alt="Preparo de Morango" />
			<a href="<?php echo $this->basepath("tabloides/Pack-Morango.zip"); ?>" class="dow_mo" target="_blank">baixar a imagem da embalagem</a>
            <a href="<?php echo $this->url('home'); ?>" class="rs" title="VOLTAR PARA HOME">Fechar</a>			
		</div>
	</div>
</div>