<div id="seletoDom">
	<div id="dom">
		<h6>café seleto<br/> apresenta </h6>
	</div>

	  <div id="logo_don_geral">
		<div id="logo_don">
			<div id="espaco"></div>
			<div id="don_logo"></div>
			<div id="espaco"></div>
		 
		</div>
      </div>



     <div id="grao">
		<div id="grao_esquerdo">
			
		</div>
		<div id="grao_direito">
			
		</div>
     </div>





</div>

<div id="seletoDom1">
   <div id="box_dom1">
		<p class="text_dom1"><span class="text_dom1">Seleto.</span><br/> Umas das marcas de café mais<br/> famosas do Brasil está de volta.</p>
	</div>
</div>

<div id="seletoDom2">
   <div id="box_dom2">
		<p class="text_dom2">E voltou melhor do que nunca, trazendo muitas<br/> novidades. Entre elas, <br/><span class="text_dom2">as cápsulas para expresso,</span></br> 
		as primeiras a serem produzidas no Brasil.</p>
	</div>



    <div id="caixa_don_geral">
		<div id="caixa_don">
			
			<div id="don_caixa"></div>
			
		</div>
    </div>

</div>


<div id="seletoDom3">
   <div id="box_dom3">
		<p class="text_dom3">São compatíveis com as máquinas Nespresso®*<br/>e vêm em 2 sabores.<br/>
			<span class="text_dom3">Intenso e Levíssimo</span></br> 
		Isso só para começar. Em breve teremos mais</br> sabores e edições especiais. Fique atento e não<br/> deixe faltar esta marca inesquecível na sua loja.</p>
			<p class="txt_nespresso">*Marca de terceiros. Não relacionada À Qualy Marcas.</p>
	</div>

	
</div>