<?php 
$this->layout()->setVariables(array('title'=>'NOSSA EMPRESA', 'keywords'=>'palavra-chave', 'descriptions'=>'descricao site'));
?>
<div id="NossaEmpresa">
	<div id="Historia">
		<h2>NOSSA EMPRESA</h2>
		<p class="txt_Empresa">O Café Seleto é uma das marcas de café mais famosas e queridas do Brasil. Também pudera. Além de ter um sabor todo especial, sempre contou com memoráveis campanhas publicitárias, e possui o jingle mais conhecido da história da propaganda brasileira. E esta grande marca está de volta ao mercado com força total. Comprada pelo Grupo Mex, o Café Seleto está de cara nova e trazendo muitas novidades também. As embalagens estão mais modernas, a campanha publicitária renovada e o café, ainda mais saboroso.</p>
		<div id="Imagens_Historia">
			<div id="missao">
				<img src="img/fundo_missao.png">
				<p class="Titulo_Missao">MISSÃO</p>
				<img class="detalhe" src="img/detalhe_missao.png">
				<p class="txt_detalhe_Missao">Produzir e fornecer produtos de qualidade, inovadores, competitivos e sustentáveis em um ambiente socialmente responsável.</p>
			</div>

			<div id="cafe">
				<img src="img/img_cafe.png">
			</div>

			<div id="visao">
				<img src="img/fundo_missao.png">
				<p class="Titulo_Visao">VISÃO</p>
				<img class="detalhe" src="img/detalhe_missao.png">
				<p class="txt_detalhe_Visao">
					Ser uma das mais conceituada e competitiva empresa alimentícia da America do<br/> 
					Sul, reconhecida pelas<br/> 
					práticas de qualidade, sustentabilidade<br/>
					e inovação.
				</p>
			</div>
		</div>
	</div>
</div>


<div id="header_empresa">
	<div id="menu_linhadotempo">
		<ul class="menu_data">
			<li value="#!container70" tabindex="1"><span title="ANOS 70">ANOS 70</span></li>			
			<li value="#!container80" tabindex="2"><span title="ANOS 80">ANOS 80</span></li>			
			<li value="#!container90" tabindex="3"><span title="ANOS 90">ANOS 90</span></li>			
			<li value="#!container13" class="enable-border" tabindex="4"><span title="Atualmente">2013</span></li>
		</ul>		
	</div>	
</div>

<div id="container_linhadotempo">

	<div id="container70" class="container" tabindex="1">
		<div id="conteudo_titulo">
			<img class="detalhe_esq" src="img/detalhe_esq.png">
			<p class="titulo">DÉCADA DE 70</p>
			<img class="detalhe_dir" src="img/detalhe_dir.png">
		</div>
		<p class="texto_container">Tudo começou nos 70, com a criação do antológico jingle por Arquimedes Messina. Primeiro no radio e depois na TV, seu sucesso foi imediato e avassalador.</p>
		<br/>
		
		<p class="texto_container">Tão grande, aliás, que nos anos seguintes foi gravado em japonês e espanhol, tocado em ritmo de fado e tango, e acabou até virando marchinha de carnaval.</p>
		<br/>
		
		<p class="texto_container">Confira a versão mais clássica do comercial, que foi ao ar pela primeira vez em 1974.</p>

		<p class="texto_video">O jingle do Café Seleto é um dos maiores clássicos da história da publicidade brasileira.</p>

		<div id="video">
			<iframe width="425" height="280" src="//www.youtube.com/embed/A-nx7__HILs" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>

	<div id="container80" class="container"  tabindex="2">
		<div id="conteudo_titulo">
			<img class="detalhe_esq" src="img/detalhe_esq.png">
			<p class="titulo">DÉCADA DE 80</p>
			<img class="detalhe_dir" src="img/detalhe_dir.png">
		</div>

		<p class="texto_container">A repercussão do filme anterior foi tão grande, que continuou fazendo sucesso durante boa parte dos anos 80.
		</p>
		<br/>
		<p class="texto_container">Em 1982, no entanto, foi produzido este outro comercial.</p>
		<br/>
		<p class="texto_container">Claro que com uma melodia tão marcante, o Café Seleto continuaria na cabeça e nos lares brasileiros por muitos e muitos anos.</p>

		<p class="texto_video">FILME DO QUARTEZINHO GENERAL</p>

		<div id="video">
			<iframe width="425" height="280" src="//www.youtube.com/embed/2ta4fhpJ4LM" frameborder="0" allowfullscreen></iframe>
		</div>

	</div>

	<div id="container90" class="container"  tabindex="3">
		<div id="conteudo_titulo">
			<img class="detalhe_esq" src="img/detalhe_esq.png">
			<p class="titulo">DÉCADA DE 90</p>
			<img class="detalhe_dir" src="img/detalhe_dir.png">
		</div>
		<p class="texto_container">Nosso café tradicional já estava consolidado como mais vendido no país.</p>
		<br/>
		
		<p class="texto_container">Chegava a hora de apresentar sua versão mais forte.</p>
		<br/>
		
		<p class="texto_container">Com muito humor e nossa infalível música ao fundo, este foi outro comercial de muito sucesso.</p>

		<p class="texto_video">Comercial do Café Seleto Extra Forte, veiculado nos anos 90.</p>

		<div id="video">
			<iframe width="425" height="280" src="//www.youtube.com/embed/Orcxdumw2Do" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>

	<div id="container13" class="container"  tabindex="4">
		<div id="conteudo_titulo">
			<img class="detalhe_esq_2013" src="img/detalhe_esq.png">
			<p class="titulo">2013</p>
			<img class="detalhe_dir_2013" src="img/detalhe_dir.png">
		</div>
		<p class="texto_container">O jingle e o café que marcaram a vida de muita gente de muita gente estão de volta.</p>
		<br/>
		
		<p class="texto_container">Com marca renovada, comercial novo e uma versão fresquinha da música que encantou gerações.</p>
		<br/>
		
		<p class="texto_container">E que, pelo jeito, vai continuar fascinando cada vez mais.</p>
		
		<p class="texto_video">Em Breve Novo Comercial do Café Seleto 2013</p>
		
		<div id="video">
			<img src="img/seleto_2013.png">
		</div>
	</div>

</div>