<?php 
$this->layout()->setVariables(array('title'=>'HOME', 'keywords'=>'palavra-chave', 'descriptions'=>'descricao site'));
?>


<div id="Home_Slide">

	<div id="Slide_geral">

		<div id="Nav_slide_geral">

			<a href="#"><span id="col_esquerda"></span></a>

			<a href="#"><span id="col_direita"></span></a>

			<ul class="slide_ul" style="left:-1024px;">
				
				<li class="slide_li">
					<a href="<?php echo $this->url('seletoDom') ?>" title="Seleto Dom"><img src="img/b_don_teste.png"></a>
				</li>				
				<li class="slide_li">
					<a href="#" class="abrirMusica"><img src="img/b_jingle_teste.png"></a>
				</li>

				<li class="slide_li">
					<a href="<?php echo $this->url('seletoDom') ?>" title="Seleto Dom"><img src="img/b_don_teste.png"></a>
				</li>
				<li class="slide_li">
					<a href="" class="abrirMusica"><img src="img/b_jingle_teste.png"></a>
				</li>
			</ul>	
			
		</div>
		
	</div>
 	



</div>  


 <div id="contentTorrefacao">
 	<div id="sombra">
 	 <img src="img/sombra.png" alt="sombra" />
 	</div>
               <div id="box_torrefacao">
                   <div class="torrefacao">
                     <h4>TORREFAÇÃO</h4>
                     <p class="subtitulo_torrefacao">E Seleto não apenas voltou para ficar, como voltou em grande estilo: está inaugurando sua Indústria de Torrefação.</p>
                     <p class="text_torrefacao">
A torrefação é onde ocorre a torra dos grãos de café e onde se estabelece o aroma e sabor final do café. Por isso, é fundamental que este processo se dê nas condições mais perfeitas possíveis. E é exatamente isso que ocorrerá na Indústria de Torrefação Seleto. Instalada em PIUMHI – MG, será uma das mais modernas da América Latina. Irá utilizar fontes de energia renováveis, será ecologicamente correta, utilizando sobras do próprio café para gerar energia. Com tecnologia de ponta continuará garantindo produtos 100% perfeito.
Por tudo isso, o Café Seleto se consolidará definitivamente - e em pouco tempo -  entre as maiores e mais importantes marcas de café do país. E com todas as credenciais para alcançar o primeiro lugar.</p>
                   </div>
               </div>
         </div>




    </div>